<?php

function nbhstats_civicrm_post( $op, $objectName, $objectId, &$objectRef ) {
	if(
		($op!='create' && $op!='edit') ||
		($objectName!='Individual' && $objectName!='Organization' && $objectName!='Household')
	){
		return;
	}
	
	//Get postcode from saved contact.
	require_once('api/v2/Contact.php');
	require_once('api/v2/Location.php');
	$params = array(
		'contact_id' => $objectId
	);
	$locations = civicrm_location_get($params);
	foreach($locations as $location){
		nbhstats_create_nbhstats_link($location['address']);
	};
		
}

function nbhstats_verify_postcode($postcode) {
	//TODO: nice (REGEXP or API) based verifcation
	
	return TRUE;
}

function nbhstats_create_nbhstats_link($address) {
	if(strlen($address['postal_code']) == 0 && nbhstats_verify_postcode($address['postal_code'])){
		$link='';
	} else {
		$link="<a href=\"http://neighbourhood.statistics.gov.uk/dissemination/NeighbourhoodSummary.do?width=0&i=0&profileSearchText={$address['postal_code']}\" target=\"_blank\">Neighbourhood stats</a>";
	}
	$address['postal_code']=urlencode($address['postal_code']);

	$params[1] = array( $address['id'], 'Integer');
	$params[2] = array( $link, 'String');
		
	CRM_Core_DAO::executeQuery("REPLACE INTO civicrm_value_neighbourhood_stats SET entity_id=%1, link=%2", $params);
}




